# Generated by Django 4.0.6 on 2022-07-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.DecimalField(decimal_places=6, max_digits=6)),
                ('sepal_width', models.DecimalField(decimal_places=6, max_digits=6)),
                ('petal_length', models.DecimalField(decimal_places=6, max_digits=6)),
                ('petal_width', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
        ),
    ]
